trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run lint
    displayName: 'Linter (ESLint)'

  - script: npm run prettier
    displayName: 'Formatter (Prettier)'

  - script: CI=true npm run test
    displayName: 'Test (Jest)'

  - script: npm run build
    displayName: 'Build'

